CREATE TABLE users
(
uid INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
firstName VARCHAR(255) NOT NULL,
lastName VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
photo VARCHAR(2048),
bio NVARCHAR(255),
rating DECIMAL,
td_id CHAR(80) NOT NULL,
CONSTRAINT IDX_USERS UNIQUE (td_id) 
);

CREATE TABLE accounts
(
td_aid CHAR(80) PRIMARY KEY NOT NULL,
td_id CHAR(80) FOREIGN KEY REFERENCES users(td_id)
);

CREATE TABLE bids
(
id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
buy TINYINT NOT NULL,
price SMALLMONEY NOT NULL,
location NVARCHAR(64) NOT NULL,
uid INT FOREIGN KEY REFERENCES users(uid),
timestamp DATETIME
);

CREATE TABLE transactions
(
td_tid CHAR(85) PRIMARY KEY,
bid_id INT FOREIGN KEY REFERENCES bids(id),
ask_id INT FOREIGN KEY REFERENCES bids(id),
status VARCHAR(255) NOT NULL,
timestamp DATETIME NOT NULL,
metadata VARCHAR(1024)
);
